require('./ast_test')
require('./fallback_test')
require('./flat_test')
require('./getkeys_test')
require('./keypath_test')
require('./objects_test')
require('./operands_test')
require('./reindex_add_test')
require('./reindex_change_test')
// require('./reindex_del_test')
// require('./siftindex_test')
// require('./todo_test')
